#!/usr/bin/env python
"""
Render docs/geoclip-location-proposals.md from scripts/.geoclip-predictions.json.

Per no-GPS photo: src, top-1 lat/lon, prob, geocoded place, sign-off checkbox.
Plus a smoke-test summary table at the top.

Read-only on photos. Idempotent.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Force UTF-8 stdout/stderr.
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[attr-defined]
except Exception:
    pass

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
PREDICTIONS_PATH = SCRIPT_DIR / ".geoclip-predictions.json"
DOC_PATH = REPO_ROOT / "docs" / "geoclip-location-proposals.md"


def render() -> None:
    with PREDICTIONS_PATH.open("r", encoding="utf-8") as f:
        data = json.load(f)

    out: list[str] = []
    push = out.append

    push("# GeoCLIP location proposals")
    push("")
    push(
        "Top-1 location proposals for portfolio photos that lack EXIF GPS, generated by "
        "[`scripts/run-geoclip.py`](../scripts/run-geoclip.py) using the open-source "
        "[GeoCLIP](https://github.com/VicenteVivan/geo-clip) image-only geolocator. "
        "The script reverse-geocodes the top-1 lat/lon via the existing Nominatim cache "
        "([`scripts/.geocode-cache.json`](../scripts/.geocode-cache.json)) so we never "
        "exceed Nominatim's 1 req/sec policy. The full top-5 is in "
        "[`scripts/.geoclip-predictions.json`](../scripts/.geoclip-predictions.json) (gitignored)."
    )
    push("")
    push(
        "**This file is for sign-off only.** Tick `- [x] approve` next to a row to greenlight it. "
        "A follow-up agent will fold approved entries into `scripts/photo-catalogue.json` "
        "(set `hasGps: true`, fill `gps`/`place`)."
    )
    push("")
    push(f"- Generated: `{data.get('generated_at')}`")
    push(f"- Model: `{data.get('model')}` (device: {data.get('device')})")
    push(f"- Top-K per photo: {data.get('top_k')}")
    push(f"- No-GPS photos processed: {data.get('no_gps_count')}")
    push("")

    # ----- Smoke test --------------------------------------------------------
    smoke = data.get("smoke_test") or {}
    samples = smoke.get("samples") or []
    push("## Smoke test (accuracy on GPS-known photos)")
    push("")
    if not samples:
        push("_No smoke test samples recorded._")
        push("")
    else:
        push("| Photo | Ground truth | GeoCLIP top-1 | prob | km error |")
        push("| --- | ---: | ---: | ---: | ---: |")
        for s in samples:
            push(
                f"| `{s['src']}` "
                f"| {s['truth_lat']:.4f}, {s['truth_lon']:.4f} "
                f"| {s['pred_lat']:.4f}, {s['pred_lon']:.4f} "
                f"| {s['pred_prob']:.4f} "
                f"| **{s['km_error']:.2f}** |"
            )
        push("")
        push(
            f"**Summary**: mean = {smoke['mean_km']:.2f} km, median = {smoke['median_km']:.2f} km, "
            f"min = {smoke['min_km']:.2f} km, max = {smoke['max_km']:.2f} km "
            f"({len(samples)} samples)."
        )
        push("")
        push(
            "Interpretation: a few-km error on city-scale photos is consistent with GeoCLIP's "
            "published accuracy on the IM2GPS3k benchmark. We consider any top-1 inside a "
            "10 km radius of the photo's existing `place_hint` city as a plausible match worth "
            "approving; values outside that radius likely indicate the model is confused (e.g. "
            "stock photo of a generic facade) and should not be auto-applied."
        )
        push("")

    # ----- Per-photo proposals ----------------------------------------------
    push("## Per-photo proposals (sign off below)")
    push("")
    push(
        "Each row: image src, GeoCLIP top-1 lat/lon and probability, the place we got back from "
        "Nominatim. The catalogue's existing `place_hint` (often manually curated for stock "
        "photos) is shown for cross-checking. **Tick the checkbox to approve**."
    )
    push("")

    # Group by trip folder for readability.
    by_trip: dict[str, list[dict]] = {}
    for p in data.get("predictions") or []:
        parts = p["src"].split("/")
        trip = parts[1] if len(parts) > 1 else "(other)"
        by_trip.setdefault(trip, []).append(p)

    for trip in sorted(by_trip.keys()):
        push(f"### `{trip}`")
        push("")
        for p in by_trip[trip]:
            top = (p.get("topK") or [None])[0]
            geocode = p.get("top1_geocode")
            hint = p.get("place_hint")
            push(f"- [ ] approve — `{p['src']}`")
            if top is None:
                push(f"  - **error**: {p.get('error', 'no prediction')}")
                continue
            geocoded_label = geocode["display"] if geocode else "(geocode unavailable)"
            push(f"  - hint: `{hint}`")
            push(
                f"  - top-1: `({top['lat']:.4f}, {top['lon']:.4f})` "
                f"prob `{top['prob']:.4f}` -> **{geocoded_label}**"
            )
        push("")

    push("---")
    push("")
    push(
        "_To regenerate: re-run `scripts/.inpaint-venv/Scripts/python.exe scripts/run-geoclip.py` "
        "then `scripts/.inpaint-venv/Scripts/python.exe scripts/generate-geoclip-doc.py`._"
    )
    push("")

    DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
    with DOC_PATH.open("w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"Wrote {DOC_PATH}")


if __name__ == "__main__":
    render()
